# Generated by Django 3.2 on 2022-11-03 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_remove_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 3)),
        ),
    ]
